services:
  postgres:
    container_name: toDoApp_db
    image: postgres
    ports:
      - "5435:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toDoApp