spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5435/toDoApp
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
postgres:
  database:
    data:
      username: user
      password: password
      url: jdbc:postgresql://localhost:5435/toDoApp