spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5435/toDoApp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db.changelog/toDoApp-changeLog.xml
postgres:
  database:
    data:
      username: user
      password: password
      url: jdbc:postgresql://localhost:5435/toDoApp
management:
  endpoints:
    web:
      exposure:
        include: '*'