spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5435/toDoApp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db.changelog/toDoApp-changeLog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/TodoApp
postgres:
  database:
    data:
      username: user
      password: password
      url: jdbc:postgresql://localhost:5435/toDoApp
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  realm: TodoApp
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: todo-app-client
  bearer-only: true
jwt:
  secret: mineageneratedabase64akeyasdasdasdasdasdasdasdasdasdasd
  validityInDays: 4